apiVersion: apps/v1
kind: Deployment
metadata:
  name: vorleser-klammeraffe
spec:
  selector:
    matchLabels:
      app: vorleser-klammeraffe
  template:
    metadata:
      labels:
        app: vorleser-klammeraffe
    spec:
      initContainers:
      - name: wait-for-all
        image: busybox
        command: ['sh', '-c']
        args:
        - |
          until nc -z vorleser-elefant 5432 && \
                nc -z vorleser-brieftaube 5672;
          do
              echo waiting for deps;
              sleep 2;
          done
      containers:
      - name: klammeraffe
        image: image-registry.openshift-image-registry.svc:5000/vorleser/vorleser-klammeraffe:latest
        env:
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-token
              key: TELEGRAM_TOKEN
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: vorleser-klammeraffe
spec:
  ports:
  - port: 5002
    targetPort: 5002
  selector:
    app: vorleser-klammeraffe